spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:staff;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    contexts: dev